default:
  # Amount in days to calculate default due date
  default_due: 14
  # Late interest, numeric value in percentage
  late_interest: 18
  # Days for complaint period
  remarking_time: 14

company:
  marketing_name: company
  name: Oy Company AB
  street: Yritystie 1
  postcode: 01234
  city: Kaupunki
  country: Finland
  telephone: +358 400 123 123
  vat: 123456
  www: https://www.company.com

email:
  from:
    address: laskut@firma.com
    name: Firma Oy - Laskut
  subject: 'Firma Oy, Lasku'
  body: 'Hei! Liitteenä laskunne.'

bank:
  name: Nordea
  iban: FI12345
  bic: NDEAFIHH

templates:
  - name: invoice-template
    title: Default
