version: '3.3'

services:
  db:
    image: postgres:10.3
    volumes:
     - dbdata:/var/lib/postgresql/data
    environment:
       POSTGRES_PASSWORD: invoicing
       POSTGRES_USER: invoicing
       MYSQL_PASSWORD: ""
    deploy:
      restart_policy:
        condition: any
  www:
      image: nginx:latest
      deploy:
        restart_policy:
          condition: any
      ports:
          - "8080:80"
      volumes:
          - .:/code
          - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      links:
          - php
  php:
      image: php-invoicing
      deploy:
        restart_policy:
          condition: any
      environment:
          COMPOSER_ALLOW_SUPERUSER: 1
      volumes:
        - .:/code
        - var-cache:/code/var/cache
        - app-vendor:/code/vendor
        - var-logs:/code/var/logs
        - var-sessions:/code/var/sessions

volumes:
    dbdata:
    app-vendor:
    var-cache:
    var-sessions:
