imports:
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    database_host: "%env(DATABASE_HOST)%"
    database_port: "%env(DATABASE_PORT)%"
    database_name: "%env(DATABASE_NAME)%"
    database_user: "%env(DATABASE_USER)%"
    database_password: "%env(DATABASE_PASSWORD)%"
    mailer_transport: "%env(MAILER_TRANSPORT)%"
    mailer_host: "%env(MAILER_HOST)%"
    mailer_user: "%env(MAILER_USER)%"
    mailer_password: "%env(MAILER_PASSWORD)%"
    secret: "%env(APP_SECRET)%"
    use_mock_mailer: "%env(bool:USE_MOCK_MAILER)%"
    server_name: "%env(SERVER_NAME)%"
    node_bin: "%env(NODE_BIN)%"

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets:
        base_path: "/api"

invoicing_app:
    database_host: "%database_host%"
    database_name: "%database_name%"
    database_user: "%database_user%"
    database_password: "%database_password%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

        types:
            invoice_status:
                class: Invoicing\DBAL\Types\InvoiceStatusType
                commented: false
        mapping_types:
            invoice_status: invoice_status

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            product:
                dir: %kernel.root_dir%/../src/Invoicing
                prefix: Invoicing
                type: annotation


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

accelerator_cache:
    host: "%server_name%"
    web_dir: "%kernel.root_dir%/../web"
