parameters:
    invoice_settings: '%kernel.project_dir%/src/Invoicing/Bundle/AppBundle/Resources/invoice/default-settings.yml'

services:
    invoicing.command.create-user:
        class: Invoicing\Bundle\AppBundle\Command\UserCreateCommand
        arguments:
            - "@invoicing.repository.user"
            - "@security.password_encoder"
        tags:
            - { name: 'console.command', command: 'user:create' }

    serialization_money_handler:
        class: Invoicing\Serializer\Handler\MoneyHandler
        tags:
            - { name: jms_serializer.subscribing_handler }
    twig.invoice.extension:
        class: Invoicing\Bundle\AppBundle\Twig\InvoiceExtension
        arguments:
            - '@file_locator'
        tags:
            - { name: twig.extension }

    invoicing.database.connection:
        class: Invoicing\Database\Connection\Connection
        arguments:
            - '%invoicing.database_host%'
            - '%invoicing.database_user%'
            - '%invoicing.database_password%'
            - '%invoicing.database_name%'

    invoicing.repository.company:
        class: Invoicing\Repository\CompanyRepository
        arguments: [Invoicing\Entity\Company]
        factory: ["@doctrine.orm.default_entity_manager", getRepository]

    invoicing.repository.parameters:
        class: Invoicing\Repository\ParametersRepository
        arguments: [Invoicing\Entity\Parameters]
        factory: ["@doctrine.orm.default_entity_manager", getRepository]

    invoicing.repository.customer:
        class: Invoicing\Repository\CustomerRepository
        arguments: [Invoicing\Entity\Customer\Customer]
        factory: ["@doctrine.orm.default_entity_manager", getRepository]

    invoicing.repository.invoice:
        class: Invoicing\Repository\InvoiceRepository
        arguments: [Invoicing\Entity\Invoice\Invoice]
        factory: ["@doctrine.orm.default_entity_manager", getRepository]

    invoicing.repository.user:
        class: Invoicing\Repository\UsaerRepository
        arguments: [Invoicing\Entity\User]
        factory: ["@doctrine.orm.default_entity_manager", getRepository]

    invoicing.repository.invoice_item:
        class: Invoicing\Repository\InvoiceItemRepository
        arguments: [Invoicing\Entity\Invoice\InvoiceItem]
        factory: ["@doctrine.orm.default_entity_manager", getRepository]

    invoicing.controller.security:
        class: Invoicing\Bundle\AppBundle\Controller\SecurityController
        arguments:
            - '@invoicing.service.invoice'
            - '@jms_serializer'

    invoicing.controller.invoice:
        class: Invoicing\Bundle\AppBundle\Controller\InvoiceController
        arguments:
            - '@invoicing.repository.invoice'
            - '@invoicing.service.sender'
            - '@invoicing.service.invoice'
            - '@jms_serializer'
            - '@invoicing.service.renderer'

    invoicing.controller.company:
        class: Invoicing\Bundle\AppBundle\Controller\CompanyController
        arguments:
            - '@invoicing.service.current_company'

    invoicing.controller.customer:
        class: Invoicing\Bundle\AppBundle\Controller\CustomerController
        arguments:
            - '@invoicing.service.customer'
            - '@jms_serializer'

    invoicing.service.invoice:
        class: Invoicing\Service\InvoiceService
        arguments:
            - '@invoicing.database.connection'
            - '@invoicing.service.customer'
            - '@invoicing.service.item'
            - '@invoicing.repository.invoice'
            - '@invoicing.value.reference_counter'
            - '%invoice_settings%'
            - '@invoicing.service.current_company'
            - '@invoicing.service.parameters'

    invoicing.service.sender:
      class: Invoicing\Service\Sender\InvoiceSenderService
      arguments: ['%use_mock_mailer%']
      factory: ["@invoicing.service.sender.factory", create]

    invoicing.service.sender.factory:
        class: Invoicing\Service\Sender\InvoiceSenderFactory
        arguments:
            - '@invoicing.service.invoice'
            - '@invoicing.service.renderer'
            - '@mailer'
            - '%invoice_settings%'

    invoicing.service.renderer:
        class: Invoicing\Service\InvoiceRendererService
        arguments:
            - '%invoice_settings%'
            - '%kernel.project_dir%'
            - '@templating'

    invoicing.service.parameters:
        class: Invoicing\Service\ParameterService
        arguments:
            - '@invoicing.service.current_company'
            - '@invoicing.repository.parameters'

    invoicing.service.current_company:
        class: Invoicing\Service\CurrentCompanyService
        arguments:
            - '@invoicing.repository.company'
            - '@session'

    invoicing.service.customer:
        class: Invoicing\Service\CustomerService
        arguments:
            - '@invoicing.repository.customer'
            - '@invoicing.database.connection'
            - '@invoicing.service.current_company'

    invoicing.service.item:
        class: Invoicing\Service\ItemService
        arguments:
            - '@invoicing.repository.invoice_item'

    invoicing.param_converter.json_deserializer:
        class: Invoicing\Bundle\AppBundle\Request\ParamConverter\JsonDeserializerParamConverter
        arguments:
            - '@jms_serializer'
            - '@validator'
            - '@invoicing.violation.error_formatter'
        tags:
            - { name: request.param_converter, priority: 0, converter: json_deserializer }

    invoicing.violation.error_formatter:
        class: Invoicing\Bundle\AppBundle\Request\Handler\ViolationErrorFormatter

    invoicing.value.reference_counter:
        class: Invoicing\Value\ReferenceCounter

    invoicing.security.logout_handler:
        class: Invoicing\Bundle\AppBundle\Security\LogoutHandler

    invoicing.listener.exception_listener:
        class: Invoicing\Bundle\AppBundle\Listener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }