services:
    invoicing.database.connection:
        class: Invoicing\Database\Connection\Connection
        arguments:
            - '%invoicing.database_host%'
            - '%invoicing.database_user%'
            - '%invoicing.database_password%'
            - '%invoicing.database_name%'

    invoicing.repository.customer:
        class: Invoicing\Repository\CustomerRepository
        arguments: [Invoicing\Entity\Customer\Customer]
        factory: ["@doctrine.orm.default_entity_manager", getRepository]

    invoicing.repository.invoice:
        class: Invoicing\Repository\InvoiceRepository
        arguments: [Invoicing\Entity\Invoice\Invoice]
        factory: ["@doctrine.orm.default_entity_manager", getRepository]

    invoicing.controller.invoice:
        class: Invoicing\Bundle\AppBundle\Controller\InvoiceController
        arguments:
            - '@invoicing.service.invoice'
            - '@serializer'

    invoicing.controller.customer:
        class: Invoicing\Bundle\AppBundle\Controller\CustomerController
        arguments:
            - '@invoicing.service.invoice'

    invoicing.service.invoice:
        class: Invoicing\Service\InvoiceService
        arguments:
            - '@invoicing.database.connection'
            - '@invoicing.service.customer'
            - '@invoicing.service.item'
            - '@invoicing.repository.invoice'
            - '@invoicing.value.reference_counter'

    invoicing.service.customer:
        class: Invoicing\Service\CustomerService
        arguments:
            - '@invoicing.repository.customer'
            - '@invoicing.database.connection'

    invoicing.service.item:
        class: Invoicing\Service\ItemService
        arguments:
            - '@invoicing.database.connection'

    invoicing.param_converter.json_deserializer:
        class: Invoicing\Bundle\AppBundle\Request\ParamConverter\JsonDeserializerParamConverter
        arguments:
            - '@jms_serializer'
            - '@validator'
            - '@invoicing.violation.error_formatter'
        tags:
            - { name: request.param_converter, priority: 0, converter: json_deserializer }

    invoicing.violation.error_formatter:
        class: Invoicing\Bundle\AppBundle\Request\Handler\ViolationErrorFormatter

    invoicing.value.reference_counter:
        class: Invoicing\Value\ReferenceCounter
