ALTER TABLE invoice DROP CONSTRAINT IF EXISTS invoice_customers CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
ALTER TABLE item DROP CONSTRAINT IF EXISTS invoice_items CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS invoice CASCADE;
DROP TYPE IF EXISTS invoice_status CASCADE;

